AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Banxico App simple deployment in a public subnet with EC2 and Elastic IP.

Parameters:
  AmiId:
    Type: String
    Description: ID de la AMI personalizada (ej: ami-0abcd1234efgh5678)
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
    Description: Tipo de instancia EC2
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Nombre del par de llaves EC2 para SSH

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: banxico-vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: banxico-igw

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: banxico-public-subnet

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  Route:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref RouteTable

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to app on 8501 and SSH
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8501
          ToPort: 8501
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: banxico-sg

Instance:
  Type: AWS::EC2::Instance
  Properties:
    ImageId: !Ref AmiId
    InstanceType: !Ref InstanceType
    KeyName: !Ref KeyPair
    SubnetId: !Ref PublicSubnet
    SecurityGroupIds:
      - !Ref SecurityGroup
    Tags:
      - Key: Name
        Value: banxico-app


  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref Instance

Outputs:
  AppPublicIP:
    Description: Public IP to access the app
    Value: !Ref ElasticIP
  AppURL:
    Description: URL de acceso
    Value: !Sub "http://${ElasticIP}:8501"
