[theme]
base="dark"
primaryColor="#4F9DDE"              # azul claro para botones/sliders
backgroundColor="#0E1117"           # fondo principal oscuro
secondaryBackgroundColor="#262730"  # sidebar y paneles
textColor="#FAFAFA"                 # texto en blanco suave
